slack_info:
    crowbot_api      : Slack API key
    bot_id           : bot user id
    group_channel_id : channel id for group channel
twilio_info:
    account_sid : AXXXXXXXXXXXXXXXXXXXXX
    auth_token : YYYYYYYYYYYYYYYYYYYYY
    from_num : Twilio activated phone number (see Twilio documentation)
telescope_info:
    lat : telescope latitude in degrees
    lon : telescope longitude in degrees
    height : telescope height in meters
kill_cmd : command that will kill the bot if sent
sos_cmd : SOS!
sos_num : Number to send SOS text messages to
sos_msg : "We need your help! --crow"
log_db_path : path to the temporary chat log database
schedule_path: path to the schedule yaml file