slack_info:
    crowbot_api      : Slack API key
    bot_id           : bot user id
    group_channel_id : channel id for group channel
telescope_info:
    lat : telescope latitude in degrees
    lon : telescope longitude in degrees
    height : telescope height in meters
kill_cmd : command that will kill the bot if sent
log_db_path : path to the temporary chat log database